spring:
  application:
    name: batch
  batch:
    jdbc:
      initialize-schema: never
  datasource:
    password: reckon12
    url: jdbc:mysql://localhost:3306/finance_db
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: finance_db
  sql:
    init:
      mode: never #change to always to run schema.sql
#logging:
#  level:
#    org.springframework.jdbc.core: DEBUG