spring:
  application:
    name: batch # Specifies the name of the application
  batch:
    jdbc:
      initialize-schema: never # Prevent Spring Batch from automatically initializing its schema
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/finance_db}  # Fallback if not set
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}  # Default password if not set
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Automatically updates database schema based on JPA entities
    show-sql: true  # Logs SQL statements executed by Hibernate
    defer-datasource-initialization: true  # Ensure schema.sql runs after Hibernate tables
    properties:
      hibernate:
        format_sql: true  # Formats SQL logs for readability
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:finance_db}
  sql:
    init:
      mode: always  # Always run schema.sql and data.sql on startup
      continue-on-error: true
